language: python

env:
  matrix:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy

sudo: false

install:
- travis_retry pip install tox

script: tox

matrix:
  fast_finish: true
