language: python

env:
  matrix:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

sudo: required

install:
- travis_retry pip install tox
- sudo apt-get install xclip

script: tox

matrix:
  fast_finish: true
