language: python

os:
  - linux
  - osx

env:
  matrix:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

sudo: false

install:
- travis_retry pip install tox

script: tox

matrix:
  fast_finish: true
